<?php
/** @var \LaPoste\ColissimoFrontPage\Block\FrontPage $block */
?>
<script type="text/javascript">
    require(
        ['LaPoste_ColissimoFrontPage/js/model/widget'],
        function (widget) {
            widget.setData(
                {
                    scriptUrl:          "<?= htmlspecialchars($block->getWidgetScriptUrl()) ?>",
                    ceCountryList:      "<?= htmlspecialchars($block->getCountryList()) ?>",
                    ceCountry:          "<?= htmlspecialchars($block->getCountry()) ?>",
                    ceLang:             "<?= htmlspecialchars($block->getStoreLanguage()) ?>",
                    dyPreparationTime:  "<?= htmlspecialchars($block->getOrderPrepareDelay()) ?>",
                    ceAddress:          "<?= json_encode(htmlspecialchars($block->getAddress()))) ?>",
                    ceZipCode:          "<?= json_encode(htmlspecialchars($block->getPostcode())) ?>",
                    ceTown:             "<?= json_encode(htmlspecialchars($block->getCity())) ?>",
                    dyWeight:           "<?= htmlspecialchars($block->getPackageWeight()) ?>",
                    token:              "<?= htmlspecialchars($block->getToken()) ?>"
                }
            );
        }
    );
</script>
